name: todoey
description: A To Do list App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette/Courgette-Regular.ttf

    - family: GloriaHallelujah
      fonts:
        - asset: assets/fonts/Gloria_Hallelujah/GloriaHallelujah-regular.ttf

    - family: Kalam
      fonts:
        - asset: assets/fonts/Kalam/Kalam-regular.ttf
        - asset: assets/fonts/Kalam/Kalam-Bold.ttf
          weight: 700

    - family: KaushanScript
      fonts:
        - asset: assets/fonts/Kaushan_Script/KaushanScript-regular.ttf

    - family: PatrickHand
      fonts:
        - asset: assets/fonts/Patrick_Hand/PatrickHand-regular.ttf

    - family: Sriracha
      fonts:
        - asset: assets/fonts/Sriracha/Sriracha-regular.ttf
